language: c
sudo: required
dist: zesty

before_install:
  - sudo apt-get install git openssl libssl-dev libfuse-dev protobuf-c-compiler libprotobuf-dev pkg-config kmod
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - git clone https://github.com/gittup/tup.git
  - (cd tup && ./bootstrap.sh)
  - sudo cp tup/tup /usr/bin/tup
  - rm -rf tup

script: ./build.sh test
