version: 2.0

references:
  default_settings: &default_settings
    working_directory: ~/mofos-client
    environment:
      LANG: C.UTF-8
  build_default: &build_default
    name: Build
    command: |
      rm -rf build
      tup release

  build_and_test: &build_and_test
    run:
      <<: *build_default
      name: Build and test

  boostrap_tup: &bootstrap_tup
    run:
      name: Build tup
      command: |
        git clone git@github.com:gittup/tup.git
        cd tup
        ./bootstrap.sh

  ubuntu_install: &ubuntu_install
    run:
      name: Install dependencies
      command: apt-get install openssl-dev fuse-dev protobuf-compiler libprotobuf-dev

  ubuntu_settings:
    <<: *default_settings
    steps:
      - *ubuntu_install
      - *bootstrap_tup
      - * build_and_test

version: 2
jobs:
  ubuntu_latest:
    <<: *ubuntu_settings
    docker:
      - image: ubuntu:zesty
